# Generated by Django 3.2 on 2024-06-06 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='页面名称')),
                ('json', models.TextField(verbose_name='页面JSON')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='关联用户')),
            ],
        ),
        migrations.CreateModel(
            name='pageJson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jsonId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jsoninfo', verbose_name='关联jsonId')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='关联用户')),
            ],
        ),
    ]
