# Generated by Django 3.2 on 2024-06-06 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jsoninfo_pagejson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pageJson',
        ),
    ]
