# Generated by Django 3.2 on 2024-06-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_pagejson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsoninfo',
            old_name='userId',
            new_name='user',
        ),
    ]
