# Generated by Django 3.2 on 2024-06-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_userid_jsoninfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsoninfo',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='jsoninfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
