# Generated by Django 3.2 on 2024-06-18 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240607_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildUniappFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=32, verbose_name='文件名')),
            ],
        ),
        migrations.AlterField(
            model_name='jsoninfo',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='关联用户'),
        ),
    ]
