# Generated by Django 3.2 on 2024-06-21 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20240618_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='builduniappfile',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.userinfo', verbose_name='关联用户'),
        ),
    ]
