# Generated by Django 4.2.13 on 2024-07-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_jsoninfo_tabbrs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsoninfo',
            old_name='tabbrs',
            new_name='tabbars',
        ),
    ]
